<?php

namespace Database\Seeders;

use App\Models\FAQ;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Schema;

class FAQSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Schema::disableForeignKeyConstraints();
        FAQ::truncate();
        Schema::enableForeignKeyConstraints();

        $faqs = [
            // Apps FAQs
            [
                'question' => 'Do you develop Android and iPhone applications?',
                'question_ar' => 'بتعملوا تطبيقات أندرويد ولا آيفون؟',
                'answer' => 'We develop both Android and iOS applications, and we can also develop a single application that works on both platforms according to your needs.',
                'answer_ar' => 'بنطوّر تطبيقات Android وiOS، وممكن كمان تطبيق واحد يشتغل على الاتنين حسب احتياجك.',
                'category' => 'apps',
                'order' => 1,
                'is_active' => true,
            ],
            [
                'question' => 'Will the application be connected to a control panel?',
                'question_ar' => 'هل التطبيق بيكون مرتبط بلوحة تحكم؟',
                'answer' => 'Yes, we provide a control panel to manage content, users, and notifications, or we connect it to your existing panel if available.',
                'answer_ar' => 'أيوه، بنوفر لوحة تحكم لإدارة المحتوى والمستخدمين والإشعارات، أو نربطه بلوحتك الحالية لو موجودة.',
                'category' => 'apps',
                'order' => 2,
                'is_active' => true,
            ],
            [
                'question' => 'Can you develop an app for my existing website?',
                'question_ar' => 'هل بتعملوا تطبيق لموقعي الحالي؟',
                'answer' => 'Definitely. If you have a website, we can create a professional application for it (WebView or full development) according to your goals, speed, and user experience requirements.',
                'answer_ar' => 'أكيد. لو عندك موقع، بنعمله تطبيق احترافي (WebView أو تطوير كامل) حسب الهدف والسرعة وتجربة المستخدم.',
                'category' => 'apps',
                'order' => 3,
                'is_active' => true,
            ],
            [
                'question' => 'When should I choose WebView and when should I develop a full native application?',
                'question_ar' => 'متى أختار WebView ومتى أعمل تطبيق تطوير كامل؟',
                'answer' => 'WebView is suitable for quick launch and lower costs.',
                'answer_ar' => 'WebView مناسب للانطلاق السريع وتكلفة أقل.',
                'category' => 'apps',
                'order' => 4,
                'is_active' => true,
            ],
            [
                'question' => 'Do you add Push Notifications?',
                'question_ar' => 'هل بتضيفوا إشعارات Push Notifications؟',
                'answer' => 'Yes, we set up custom notifications (offers/alerts/news) with the ability to control them from the admin panel.',
                'answer_ar' => 'أيوه، بنجهز إشعارات مخصصة (عروض/تنبيهات/أخبار) مع إمكانية التحكم فيها من لوحة الإدارة.',
                'category' => 'apps',
                'order' => 5,
                'is_active' => true,
            ],
            [
                'question' => 'Will the application be fast and responsive?',
                'question_ar' => 'هل التطبيق بيكون سريع ومتجاوب؟',
                'answer' => 'We focus on performance: lightweight screens, compressed images, and load time optimization so users don\'t feel any slowness.',
                'answer_ar' => 'بنركز على الأداء: شاشات خفيفة، صور مضغوطة، وتحسين التحميل علشان المستخدم مايحسش ببطء.',
                'category' => 'apps',
                'order' => 6,
                'is_active' => true,
            ],
            [
                'question' => 'Do you design UI/UX for the application?',
                'question_ar' => 'هل بتعملوا تصميم UI/UX للتطبيق؟',
                'answer' => 'Yes, we design an easy and clear interface, and create a user experience suitable for your audience.',
                'answer_ar' => 'أيوه، بنصمم واجهة سهلة وواضحة، ونعمل تجربة مستخدم مناسبة لطبيعة جمهورك.',
                'category' => 'apps',
                'order' => 7,
                'is_active' => true,
            ],
            [
                'question' => 'How do you determine the cost of application development?',
                'question_ar' => 'إزاي بتحددوا تكلفة برمجة التطبيق؟',
                'answer' => 'The cost is determined based on the number of screens, type of registration (phone/email), control panel, electronic payment, notifications, and third-party integrations.',
                'answer_ar' => 'التكلفة بتتحدد حسب عدد الشاشات، نوع التسجيل (هاتف/إيميل)، لوحة التحكم، الدفع الإلكتروني، الإشعارات، وتكاملات الطرف الثالث.',
                'category' => 'apps',
                'order' => 8,
                'is_active' => true,
            ],
            [
                'question' => 'Do you help in uploading the application to Google Play and App Store?',
                'question_ar' => 'هل بتساعدوا في رفع التطبيق على Google Play وApp Store؟',
                'answer' => 'Yes, we prepare the publishing files, images and description, and help you with the upload steps and required settings.',
                'answer_ar' => 'أيوه، بنجهز ملفات النشر، الصور والوصف، ونساعدك في خطوات الرفع والإعدادات المطلوبة.',
                'category' => 'apps',
                'order' => 9,
                'is_active' => true,
            ],
            [
                'question' => 'Is there maintenance and updates after delivery?',
                'question_ar' => 'هل في صيانة وتحديثات بعد التسليم؟',
                'answer' => 'Of course. We provide support, maintenance, and updates according to the package, so the application remains stable with system updates.',
                'answer_ar' => 'أكيد. بنقدم دعم وصيانة وتحديثات حسب الباقة، علشان التطبيق يفضل مستقر مع تحديثات الأنظمة.',
                'category' => 'apps',
                'order' => 10,
                'is_active' => true,
            ],

            // Websites FAQs
            [
                'question' => 'Do you design websites for any type of business?',
                'question_ar' => 'بتصمموا مواقع لأي نوع نشاط؟',
                'answer' => 'Yes, we design company websites, service websites, e-commerce stores, and corporate profiles according to your goals and audience.',
                'answer_ar' => 'أيوه، بنصمم مواقع شركات، مواقع خدمات، متاجر إلكترونية، وبروفايل تعريفي—حسب هدفك وجمهورك.',
                'category' => 'websites',
                'order' => 1,
                'is_active' => true,
            ],
            [
                'question' => 'Will the website be responsive on mobile?',
                'question_ar' => 'الموقع هيكون متجاوب على الموبايل؟',
                'answer' => 'Absolutely. We implement a fully responsive design for mobile, tablet, and desktop, with fast and easy browsing experience.',
                'answer_ar' => 'أكيد. بننفّذ تصميم Responsive كامل للموبايل والتابلت والكمبيوتر، مع تجربة تصفح سريعة وسهلة.',
                'category' => 'websites',
                'order' => 2,
                'is_active' => true,
            ],
            [
                'question' => 'How long does it take to develop a website?',
                'question_ar' => 'مدة تنفيذ الموقع قد إيه؟',
                'answer' => 'The duration depends on the number of pages and required features, and is usually 7 to 21 days for company and service websites.',
                'answer_ar' => 'المدة بتتحدد حسب عدد الصفحات والوظائف المطلوبة، وغالبًا بتكون من 7 إلى 21 يوم لمواقع الشركات والخدمات.',
                'category' => 'websites',
                'order' => 3,
                'is_active' => true,
            ],
            [
                'question' => 'Will I be able to edit the content myself after delivery?',
                'question_ar' => 'هل هقدر أعدّل المحتوى بنفسي بعد التسليم؟',
                'answer' => 'Yes, we provide you with a clear control panel where you can easily edit texts, images, services, and add pages.',
                'answer_ar' => 'أيوه، بنسلمك لوحة تحكم واضحة تقدر من خلالها تعدّل النصوص والصور والخدمات وتضيف صفحات بسهولة.',
                'category' => 'websites',
                'order' => 4,
                'is_active' => true,
            ],
            [
                'question' => 'Do you prepare the website for SEO from the beginning?',
                'question_ar' => 'هل بتجهزوا الموقع للسيو من البداية؟',
                'answer' => 'We prepare the website technically for SEO: organized headings, clean links, fast loading, and basic optimization that helps pages be indexed and competitive.',
                'answer_ar' => 'بنجهّز الموقع فنيًا للسيو: عناوين منظمة، روابط نظيفة، سرعة تحميل، وتهيئة أساسية تساعد الصفحات تتفهرس وتنافس.',
                'category' => 'websites',
                'order' => 5,
                'is_active' => true,
            ],
            [
                'question' => 'Do you provide content for pages or do I need to write it?',
                'question_ar' => 'هل بتوفروا محتوى للصفحات ولا لازم أنا أكتبه؟',
                'answer' => 'We can write content professionally and SEO-compatible, or review your content and organize it before publishing.',
                'answer_ar' => 'نقدر نكتب المحتوى بشكل احترافي ومتوافق مع السيو، أو نراجع محتواك ونرتّبه ونظبطه قبل النشر.',
                'category' => 'websites',
                'order' => 6,
                'is_active' => true,
            ],
            [
                'question' => 'Is there warranty or support after delivery?',
                'question_ar' => 'هل في ضمان أو دعم بعد التسليم؟',
                'answer' => 'There is technical support according to the package, which includes issue follow-up, basic updates, and assistance with necessary additions.',
                'answer_ar' => 'في دعم فني حسب الباقة، ويشمل متابعة المشاكل، تحديثات أساسية، ومساعدة في الإضافات الضرورية.',
                'category' => 'websites',
                'order' => 7,
                'is_active' => true,
            ],
            [
                'question' => 'Do you customize the design or use a ready-made template?',
                'question_ar' => 'هل بتعملوا تصميم مخصص ولا قالب جاهز؟',
                'answer' => 'We choose the most appropriate based on budget and goal: fully custom design or professional design built on a ready-made system with powerful modifications.',
                'answer_ar' => 'بنختار الأنسب حسب الميزانية والهدف: تصميم مخصص بالكامل أو تصميم احترافي مبني على نظام جاهز مع تعديلات قوية.',
                'category' => 'websites',
                'order' => 8,
                'is_active' => true,
            ],
            [
                'question' => 'Can you connect the website with WhatsApp, calls, and forms?',
                'question_ar' => 'هل بتقدروا تربطوا الموقع بواتساب واتصال ونماذج؟',
                'answer' => 'Yes, we create WhatsApp/call buttons, contact forms, and connect email and notifications appropriately.',
                'answer_ar' => 'أيوه، بنعمل أزرار واتساب/اتصال، نماذج تواصل، وربط البريد والإشعارات بالطريقة المناسبة.',
                'category' => 'websites',
                'order' => 9,
                'is_active' => true,
            ],
            [
                'question' => 'How do I start with you and get a quote?',
                'question_ar' => 'إزاي أبدأ معاكم وأخد عرض سعر؟',
                'answer' => 'Send us your business type + example websites you like + number of required pages, and we\'ll get back to you with a clear vision and appropriate pricing.',
                'answer_ar' => 'ابعت نوع نشاطك + مثال مواقع تعجبك + عدد الصفحات المطلوبة، وهنرجعلك بتصور واضح وتكلفة مناسبة.',
                'category' => 'websites',
                'order' => 10,
                'is_active' => true,
            ],

            // Domains FAQs
            [
                'question' => 'How do I choose a strong domain name?',
                'question_ar' => 'إزاي أختار اسم دومين قوي؟',
                'answer' => 'Make it short, easy to pronounce and spell, close to your brand name, and preferably without numbers or hyphens if possible.',
                'answer_ar' => 'خليه قصير، سهل النطق والكتابة، قريب من اسم البراند، ويفضل بدون أرقام أو شرطات لو أمكن.',
                'category' => 'domains',
                'order' => 1,
                'is_active' => true,
            ],
            [
                'question' => 'Which extension is better: .com, .net, or .org?',
                'question_ar' => 'أنهي امتداد أفضل: .com ولا .net ولا .org؟',
                'answer' => 'If your business is technical, .net might be suitable, and if it\'s an organization/association, .org might be suitable. Most importantly, it should be appropriate for the brand and easy to remember.',
                'answer_ar' => 'لو نشاطك تقني ممكن .net، ولو مؤسسة/جمعية ممكن .org. الأهم يكون مناسب للبراند وسهل التذكر.',
                'category' => 'domains',
                'order' => 2,
                'is_active' => true,
            ],
            [
                'question' => 'Does the domain affect SEO?',
                'question_ar' => 'هل الدومين بيأثر على السيو؟',
                'answer' => 'The name itself is not "magic", but a clear domain name and strong brand help with trust and clicks, which reflects on performance.',
                'answer_ar' => 'الاسم نفسه مش "سحر"، لكن الدومين الواضح والبراند القوي بيساعد في الثقة والضغطات، وده ينعكس على الأداء.',
                'category' => 'domains',
                'order' => 3,
                'is_active' => true,
            ],
            [
                'question' => 'Do you provide domain protection (Domain Privacy)?',
                'question_ar' => 'هل بتوفروا حماية الدومين (Domain Privacy)؟',
                'answer' => 'If available for the extension, we enable privacy to reduce spam and protect owner information in WHOIS.',
                'answer_ar' => 'لو متاحة حسب الامتداد، بنفعّل الخصوصية لتقليل السبام وحماية بيانات المالك في WHOIS.',
                'category' => 'domains',
                'order' => 4,
                'is_active' => true,
            ],
            [
                'question' => 'Can you connect the domain to the website and hosting?',
                'question_ar' => 'هل بتقدروا تربطوا الدومين بالموقع والاستضافة؟',
                'answer' => 'Yes, we configure DNS and connect the domain to the server + SSL and run the website completely.',
                'answer_ar' => 'أيوه، بنضبط DNS وربط الدومين بالسيرفر + SSL وتشغيل الموقع بالكامل.',
                'category' => 'domains',
                'order' => 5,
                'is_active' => true,
            ],
            [
                'question' => 'What does DNS, A Record, and CNAME mean?',
                'question_ar' => 'يعني إيه DNS وA Record وCNAME؟',
                'answer' => 'These are settings that determine which server or service the domain goes to. We configure them correctly for you according to your hosting.',
                'answer_ar' => 'دي إعدادات بتحدد الدومين يروح لأي سيرفر أو خدمة. إحنا بنظبطها لك بالشكل الصحيح حسب الاستضافة.',
                'category' => 'domains',
                'order' => 6,
                'is_active' => true,
            ],
            [
                'question' => 'Can I transfer the domain from one company to another?',
                'question_ar' => 'هل ممكن أنقل الدومين من شركة لشركة؟',
                'answer' => 'Yes, the transfer is easy provided the transfer code (Auth Code) is available and there is no transfer lock, and we help you step by step.',
                'answer_ar' => 'أيوه، النقل ممكن بسهولة بشرط توفر كود النقل (Auth Code) وعدم وجود قفل نقل، وإحنا نساعدك خطوة بخطوة.',
                'category' => 'domains',
                'order' => 7,
                'is_active' => true,
            ],
            [
                'question' => 'Do you enable SSL for free?',
                'question_ar' => 'هل بتفعلوا SSL مجانًا؟',
                'answer' => 'If the hosting supports Let\'s Encrypt, we enable free SSL so the website runs securely with https.',
                'answer_ar' => 'لو الاستضافة تدعم Let\'s Encrypt، بنفعّل SSL مجاني علشان الموقع يشتغل https بأمان.',
                'category' => 'domains',
                'order' => 8,
                'is_active' => true,
            ],
            [
                'question' => 'What is the domain registration period?',
                'question_ar' => 'إيه مدة حجز الدومين؟',
                'answer' => 'Usually one year eligible for renewal, and you can register for several years in advance if you prefer.',
                'answer_ar' => 'غالبًا سنة قابلة للتجديد، وتقدر تحجز لسنين مقدّمًا لو تحب.',
                'category' => 'domains',
                'order' => 9,
                'is_active' => true,
            ],
            [
                'question' => 'What should I do if the domain is taken?',
                'question_ar' => 'لو الدومين محجوز أعمل إيه؟',
                'answer' => 'We suggest nearby alternatives (different extension/shorter name/adding a simple word) while maintaining the same brand meaning.',
                'answer_ar' => 'بنقترح بدائل قريبة (امتداد مختلف/اسم أقصر/إضافة كلمة بسيطة) مع الحفاظ على نفس معنى البراند.',
                'category' => 'domains',
                'order' => 10,
                'is_active' => true,
            ],

            // Hosting FAQs
            [
                'question' => 'What type of hosting is best for my website?',
                'question_ar' => 'إيه نوع الاستضافة الأنسب لموقعي؟',
                'answer' => 'If you have a small company website: strong shared hosting is enough. If you have a store or a website with high traffic: VPS or cloud hosting is better for performance and stability.',
                'answer_ar' => 'لو موقع شركة صغير: استضافة مشتركة قوية تكفي. لو متجر أو موقع زياراته عالية: الأفضل VPS أو سحابي علشان الأداء والثبات.',
                'category' => 'hosting',
                'order' => 1,
                'is_active' => true,
            ],
            [
                'question' => 'Does hosting affect the website speed?',
                'question_ar' => 'هل الاستضافة بتأثر على سرعة الموقع؟',
                'answer' => 'Of course. A powerful server + cache settings + CDN make a big difference in loading speed and user experience.',
                'answer_ar' => 'طبعًا. السيرفر القوي + إعدادات الكاش + CDN بيصنعوا فرق كبير في سرعة التحميل وتجربة المستخدم.',
                'category' => 'hosting',
                'order' => 2,
                'is_active' => true,
            ],
            [
                'question' => 'Do you provide automatic backups?',
                'question_ar' => 'هل عندكم نسخ احتياطي تلقائي؟',
                'answer' => 'Yes, we provide periodic backups, and we can schedule according to package (daily/weekly).',
                'answer_ar' => 'أيوه، بنوفر نسخ احتياطي دوري، ونقدر نحدد الجدول حسب الباقة (يومي/أسبوعي).',
                'category' => 'hosting',
                'order' => 3,
                'is_active' => true,
            ],
            [
                'question' => 'Is there protection against hacking and spam?',
                'question_ar' => 'هل في حماية ضد الاختراق والسبام؟',
                'answer' => 'We enable basic layers of protection (Firewall/block login attempts/file protection) with monitoring as needed.',
                'answer_ar' => 'بنفعّل طبقات حماية أساسية (Firewall/حظر محاولات الدخول/حماية الملفات) مع متابعة حسب الحاجة.',
                'category' => 'hosting',
                'order' => 4,
                'is_active' => true,
            ],
            [
                'question' => 'Can you migrate my website from one hosting to another?',
                'question_ar' => 'هل تقدروا تنقلوا موقعي من استضافة لاستضافة؟',
                'answer' => 'Yes, we do complete website migration with testing before final delivery.',
                'answer_ar' => 'أيوه، بنعمل Migration كامل للموقع مع اختبار قبل تسليم التشغيل النهائي.',
                'category' => 'hosting',
                'order' => 5,
                'is_active' => true,
            ],
            [
                'question' => 'Does hosting include an official company email?',
                'question_ar' => 'هل الاستضافة تشمل بريد إلكتروني رسمي للشركة؟',
                'answer' => 'We can provide an official email in your domain name (example: info@yourdomain.com) and set it up on your phone and computer.',
                'answer_ar' => 'نقدر نوفر بريد رسمي باسم الدومين (مثال: info@yourdomain.com) وإعداده على الهاتف والكمبيوتر.',
                'category' => 'hosting',
                'order' => 6,
                'is_active' => true,
            ],
            [
                'question' => 'Is there technical support if something goes wrong?',
                'question_ar' => 'هل في دعم فني لو حصلت مشكلة؟',
                'answer' => 'Yes, technical support to resolve issues and monitor performance according to your package, with higher priority for larger packages.',
                'answer_ar' => 'أيوه، دعم فني لحل الأعطال ومتابعة الأداء حسب الباقة، مع أولوية أعلى للباقات الأكبر.',
                'category' => 'hosting',
                'order' => 7,
                'is_active' => true,
            ],
            [
                'question' => 'What is the difference between SSD and NVMe?',
                'question_ar' => 'إيه الفرق بين SSD وNVMe؟',
                'answer' => 'NVMe is faster than SSD in reading and writing, which improves website performance especially in control panels and databases.',
                'answer_ar' => 'الـ NVMe أسرع من SSD في القراءة والكتابة، وده بيحسن أداء المواقع خصوصًا في لوحات التحكم وقواعد البيانات.',
                'category' => 'hosting',
                'order' => 8,
                'is_active' => true,
            ],
            [
                'question' => 'Is the hosting suitable for WordPress?',
                'question_ar' => 'هل الاستضافة مناسبة لووردبريس؟',
                'answer' => 'Yes, and we configure WordPress basic settings to be stable and fast (PHP/Cache/Permissions) according to the server.',
                'answer_ar' => 'أيوه، وبنظبط إعدادات ووردبريس الأساسية لتكون مستقرة وسريعة (PHP/Cache/Permissions) حسب السيرفر.',
                'category' => 'hosting',
                'order' => 9,
                'is_active' => true,
            ],
            [
                'question' => 'Can I upgrade later if my website grows?',
                'question_ar' => 'هل فيه ترقية لاحقًا لو موقعي كبر؟',
                'answer' => 'Definitely. You can start with an appropriate plan and easily upgrade to VPS or higher resources without stopping the website for long.',
                'answer_ar' => 'أكيد. تقدر تبدأ بخطة مناسبة وتترقى بسهولة لـ VPS أو موارد أعلى بدون ما توقف الموقع لفترة طويلة.',
                'category' => 'hosting',
                'order' => 10,
                'is_active' => true,
            ],
            [
                'question' => 'Is there a possibility to get a refund?',
                'question_ar' => 'هل هل في امكانية استرجاع الاموال',
                'answer' => 'Yes, there is a possibility to get a refund in the following cases: if the service has a problem, and this is within 14 days of receiving the service.',
                'answer_ar' => 'اه في امكانية استرجاع الاموال في الحالات التالية وهي ان الخدمة يكون فيها مشكلة وده في خلال 14 يوم من استلام الخدمة ',
                'category' => 'hosting',
                'order' => 11,
                'is_active' => true,
            ],

            // Services Marketing FAQs
            [
                'question' => 'What services do you offer in digital marketing?',
                'question_ar' => 'إيه الخدمات اللي بتقدموها في التسويق الإلكتروني؟',
                'answer' => 'We offer comprehensive services including: Google ads, social media ads, SEO, social media management, content writing, landing page design, and performance analysis and reporting.',
                'answer_ar' => 'بنقدم خدمات متكاملة تشمل: إعلانات جوجل، إعلانات السوشيال ميديا، تحسين محركات البحث (SEO)، إدارة صفحات السوشيال، كتابة المحتوى، تصميم صفحات هبوط، وتحليل وتقارير الأدا',
                'category' => 'services-marketing',
                'order' => 1,
                'is_active' => true,
            ],
            [
                'question' => 'Is digital marketing suitable for my business?',
                'question_ar' => 'هل التسويق الإلكتروني مناسب لنشاطي؟',
                'answer' => 'Yes, we determine what\'s best according to your business type (services/products) and target audience, and choose the channels that achieve the best results with the lowest cost.',
                'answer_ar' => 'أيوه، بنحدد الأنسب حسب نوع نشاطك (خدمات/منتجات) والجمهور المستهدف، وبنختار القنوات اللي تحقق أفضل نتيجة بأقل تكلفة.',
                'category' => 'services-marketing',
                'order' => 2,
                'is_active' => true,
            ],
            [
                'question' => 'When will I see actual results?',
                'question_ar' => 'إمتى أشوف نتائج فعلية؟',
                'answer' => 'Paid ads show results within a few days, while SEO results usually take 2 to 6 months depending on competition and your website\'s condition.',
                'answer_ar' => 'الإعلانات الممولة نتائجها بتبدأ خلال أيام قليلة، أما السيو (SEO) نتائجه بتحتاج عادة من 2 إلى 6 شهور حسب المنافسة وحالة موقعك.',
                'category' => 'services-marketing',
                'order' => 3,
                'is_active' => true,
            ],
            [
                'question' => 'Do you guarantee results?',
                'question_ar' => 'هل بتضمنوا نتائج؟',
                'answer' => 'We guarantee professional work based on data and continuous improvement, but results are affected by factors like competition, budget, and offer quality. What we guarantee: monitoring, development, and clear reports with numbers.',
                'answer_ar' => 'بنضمن شغل احترافي مبني على بيانات وتحسين مستمر، لكن النتائج بتتأثر بعوامل زي المنافسة والميزانية وجودة العرض. اللي بنضمنه: متابعة، تطوير، وتقارير واضحة بالأرقام.',
                'category' => 'services-marketing',
                'order' => 4,
                'is_active' => true,
            ],
            [
                'question' => 'How do you determine the appropriate budget for ads?',
                'question_ar' => 'إزاي بتحددوا الميزانية المناسبة للإعلانات؟',
                'answer' => 'We determine it based on your goal (calls/WhatsApp/sales) and field cost, and suggest a practical budget that starts gradually and increases as results improve.',
                'answer_ar' => 'بنحددها حسب هدفك (مكالمات/واتساب/مبيعات) وتكلفة المجال، وبنقترح ميزانية عملية تبدأ تدريجيًا ثم نرفعها مع تحسن النتائج.',
                'category' => 'services-marketing',
                'order' => 5,
                'is_active' => true,
            ],
            [
                'question' => 'Will you get me customers (calls/WhatsApp)?',
                'question_ar' => 'هل هتجيبولي عملاء (مكالمات/واتساب)؟',
                'answer' => 'Our main goal is to increase potential customers through targeted campaigns + powerful landing page + tracking calls and WhatsApp to continuously improve results.',
                'answer_ar' => 'هدفنا الأساسي هو زيادة العملاء المحتملين عبر حملات موجهة + صفحة هبوط قوية + تتبع المكالمات والواتساب لتحسين النتائج باستمرار.',
                'category' => 'services-marketing',
                'order' => 6,
                'is_active' => true,
            ],
            [
                'question' => 'What is the difference between Google ads and social media ads?',
                'question_ar' => 'إيه الفرق بين إعلانات جوجل وإعلانات السوشيال؟',
                'answer' => '<p>Google: Excellent for those searching for the service "right now".</p><p>Social: Excellent for reach, engagement, building demand, and retargeting.</p>',
                'answer_ar' => '<p>جوجل: ممتاز للي بيبحث عن الخدمة "دلوقتي".</p><p>السوشيال: ممتاز للانتشار والتفاعل وبناء الطلب وإعادة الاستهداف.</p>',
                'category' => 'services-marketing',
                'order' => 7,
                'is_active' => true,
            ],
            [
                'question' => 'Do I need to have a website?',
                'question_ar' => 'هل لازم يكون عندي موقع؟',
                'answer' => 'Not required, we can start with a landing page or WhatsApp, but having a strong website increases trust and helps with SEO and conversion improvement.',
                'answer_ar' => 'مش شرط، نقدر نبدأ بـ صفحة هبوط أو واتساب، لكن وجود موقع قوي بيزود الثقة ويساعد في السيو وتحسين التحويل.',
                'category' => 'services-marketing',
                'order' => 8,
                'is_active' => true,
            ],
            [
                'question' => 'Do you design a professional landing page?',
                'question_ar' => 'هل بتجهزوا صفحة هبوط احترافية؟',
                'answer' => 'Yes, we design a professional landing page aimed at converting visitors to customers: strong headline, clear features, WhatsApp/call button, request forms, and excellent speed.',
                'answer_ar' => 'أيوه، بنصمم صفحة هبوط هدفها تحويل الزائر لعميل: عنوان قوي، مزايا واضحة، زر واتساب/اتصال، نماذج طلب، وسرعة ممتازة.',
                'category' => 'services-marketing',
                'order' => 9,
                'is_active' => true,
            ],
            [
                'question' => 'Do you provide consultation before contracting?',
                'question_ar' => 'هل بتقدموا استشارة قبل التعاقد؟',
                'answer' => 'Yes, we have a short session to understand your goal and suggest the best plan suitable for your budget.',
                'answer_ar' => 'أيوه، بنعمل جلسة قصيرة نفهم فيها هدفك ونقترح أفضل خطة مناسبة لميزانيتك.',
                'category' => 'services-marketing',
                'order' => 10,
                'is_active' => true,
            ],
            [
                'question' => 'What do you need from me to start?',
                'question_ar' => 'يه اللي محتاجينه منّي علشان نبدأ؟',
                'answer' => 'We need: business type + city/country + services/products + approximate budget + WhatsApp number + any offers or prices (if available).',
                'answer_ar' => 'نحتاج: نوع النشاط + المدينة/الدولة + الخدمات/المنتجات + الميزانية التقريبية + رقم واتساب + أي عروض أو أسعار (لو متاحة).',
                'category' => 'services-marketing',
                'order' => 11,
                'is_active' => true,
            ],
        ];

        foreach ($faqs as $faq) {
            FAQ::create($faq);
        }
    }
}
