<?php

return [
    'defaults' => [
        'home_hero_section' => 200,
        'home_services_section' => 60,
        'home_projects_section' => 20,
        'home_reviews_section' => 60,
        'home_clients_section' => 120,
        'about_us_line_works_steps_section' => 60,
        'about_us_partners_section' => 60,
        'portfolio_section' => 200,
        'blog_articles_section' => 60,
        'articles_page_section' => 200,
        'tickets_section' => 180,
        'website_developer_section' => 120,
        'website_programming_section' => 200,
        'website_design_section' => 60,
        'important_articles_section' => 100,
        'faqs_section' => 60,
        'app_developer_hero_section' => 240,
        'order_your_app_section' => 170,
        'categories_programming_section' => 200,
        'projects_steps_section' => 60,
        'hosting_hero_section' => 60,
        'hosting_features_section' => 200,
        'hosting_packages_section' => 120,
        'support_hosting_section' => 120,
        'operations_systems_section' => 60,
        'your_domain_section' => 240,
        'pest_domains_section' => 60,
        'official_domains_section' => 120,
        'why_us_section' => 120,
        'marketing_hero_section' => 240,
        'platform_management_section' => 60,
        'work_lines_section' => 120,
        'dont_worry_hosting_section' => 60,
        'easy_management_section' => 60,
        'packages_marketing_section' => 120,
    ],
];