<?php

return [
    [
        'title' => 'الفــــهد للدعاية والاعلان',
        'description' => 'شركة الفهد للدعاية والاعلان',
        'image' => '1.jpg',
        'order' => 1,
        'tags' => ['web_design', 'graphic_design'],
    ],
    [
        'title' => 'فاطمة لتحفيظ القران',
        'description' => 'فاطمة لتحفيظ القران للكبار والصغار',
        'image' => '2.jpg',
        'order' => 2,
        'tags' => ['web_design', 'graphic_design'],
    ],
    [
        'title' => 'شركة الدوليــــة',
        'description' => 'شركة الدوليــــة للخدمات المتنوعة',
        'image' => '3.jpg',
        'order' => 3,
        'tags' => ['web_design'],
    ],
    [
        'title' => 'الوصل للذبائح',
        'description' => 'شركة لبيع منتجات الذبائح بالامارات',
        'image' => '4.jpg',
        'order' => 4,
        'tags' => ['web_design', 'graphic_design'],
    ],
    [
        'title' => 'شركة ميديا للاجهزه',
        'description' => 'شركة ميديا للاجهزه المنزلية',
        'image' => '5.jpg',
        'order' => 5,
        'tags' => ['graphic_design'],
    ],
    [
        'title' => 'بالعافية للذبائح',
        'description' => 'شركة بيع منتجات الذبائح بالامارات',
        'image' => '6.jpg',
        'order' => 6,
        'tags' => ['web_design'],
    ],
    [
        'title' => 'كونسبت ميديا',
        'description' => 'شركة كونسبت ميديا للانتاج الفني',
        'image' => '7.jpg',
        'order' => 7,
        'tags' => ['web_design', 'graphic_design'],
    ],
    [
        'title' => 'شــركة ATA',
        'description' => 'بيع منتجات الاجهزه الكهربائية والمنزلية',
        'image' => '8.jpg',
        'order' => 8,
        'tags' => ['web_design', 'graphic_design'],
    ],
    [
        'title' => 'توب وان كلين',
        'description' => 'شركة مكافحة حشرات بالكويت',
        'image' => '9.jpg',
        'order' => 9,
        'tags' => ['web_design'],
    ],
    [
        'title' => 'شركة دهانات',
        'description' => 'شركة دهانات جي ال سي',
        'image' => '10.jpg',
        'order' => 10,
        'tags' => ['graphic_design'],
    ],
    [
        'title' => 'البصرة لايف 25',
        'description' => 'منصة بث لايف وبودكاست البصرة 25',
        'image' => '11.jpg',
        'order' => 11,
        'tags' => ['web_design', 'graphic_design'],
    ],
    [
        'title' => 'شركة هوم لايف',
        'description' => 'شركة هوم لايف لتنسيق الحدائق بالرياض',
        'image' => '12.jpg',
        'order' => 12,
        'tags' => ['web_design'],
    ],
    [
        'title' => 'منصة الالفية التعليمية',
        'description' => 'منصة كورسات تعليمية بالاردن',
        'image' => '13.jpg',
        'order' => 13,
        'tags' => ['web_design', 'graphic_design'],
    ],
    [
        'title' => 'الطيب للذبائح',
        'description' => 'شركة الطيب للذبائح بدولة الامارات',
        'image' => '14.jpg',
        'order' => 14,
        'tags' => ['graphic_design'],
    ],
    [
        'title' => 'مباردة بنك السعادة',
        'description' => 'مؤسسة رسمية بدولة الامارات',
        'image' => '15.jpg',
        'order' => 15,
        'tags' => ['web_design', 'graphic_design'],
    ],
    [
        'title' => 'شركة العز اكسبريس',
        'description' => 'موقع وسيستم شحن – العز اكسبريس',
        'image' => '16.jpg',
        'order' => 16,
        'tags' => ['web_design'],
    ],
    [
        'title' => 'الرحمة لتصدير المنتجات',
        'description' => 'شركة استيرداد وتصدير منتجات زراعية',
        'image' => '17.jpg',
        'order' => 17,
        'tags' => ['web_design', 'graphic_design'],
    ],
    [
        'title' => 'كيمت التطوير العقاري',
        'description' => 'شركة متخصصة في التطوير العقاري والمشروعات العقارية',
        'image' => '18.jpg',
        'order' => 18,
        'tags' => ['web_design'],
    ],
    [
        'title' => 'سمارت بور',
        'description' => 'موقع خاص بالمعدات الصناعية للمصانع واصحاب المهن',
        'image' => '19.jpg',
        'order' => 19,
        'tags' => ['web_design', 'graphic_design'],
    ],
    [
        'title' => 'الحدث اليوم نيوز',
        'description' => 'موقع اخباري متميز',
        'image' => '20.jpg',
        'order' => 20,
        'tags' => ['web_design'],
    ],
];
