<?php

return [
    'inline_padding' => [
        'home_hero_section' => 200,
        'home_services_section' => 180,
        'home_projects_section' => 20,
        'home_reviews_section' => 220,
        'home_clients_section' => 120,
        'about_us_line_works_steps_section' => 60,
        'about_us_partners_section' => 60,
        'portfolio_section' => 200,
        'blog_articles_section' => 60,
        'articles_page_section' => 200,
        'blog_show_section' => 120,
        'tickets_section' => 180,
        'website_developer_section' => 120,
        'website_programming_section' => 200,
        'website_design_section' => 60,
        'important_articles_section' => 100,
        'faqs_section' => 60,
        'app_developer_hero_section' => 240,
        'order_your_app_section' => 170,
        'categories_programming_section' => 200,
        'projects_steps_section' => 60,
        'hosting_hero_section' => 60,
        'hosting_features_section' => 200,
        'hosting_packages_section' => 160,
        'support_hosting_section' => 180,
        'operations_systems_section' => 200,
        'your_domain_section' => 240,
        'pest_domains_section' => 300,
        'official_domains_section' => 120,
        'why_us_section' => 300,
        'marketing_hero_section' => 240,
        'platform_management_section' => 60,
        'work_lines_section' => 120,
        'dont_worry_hosting_section' => 120,
        'easy_management_section' => 60,
        'packages_marketing_section' => 120,
    ],
    'colors' => [
        'dash_primary_color' => '#F54900',
        'text_color' => '#ffffff',
        'icon_color' => '#4a5565',
        'button_color' => '#0074F7',

        // Website colors
        'main_color' => '#d05423',
        'light_main_color' => '#F97316',
        'dark_main_color' => '#96310E',
    ]
];
